name: Continuous integration pipeline
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-sample_application:
    name: Build the sample application binary
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi
      - name: Build the sample_application binary
        working-directory: app
        shell: bash
        run: |
          west build -b b_l4s5i_iot01a
      - name: Upload sample_application artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: zephyr-sample_application
          path: app/build/zephyr/zephyr.*
