name: Continuous integration pipeline
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-sample_application:
    name: Build the sample application binary
    runs-on: ubuntu-24.04
    container:
      image: zephyrprojectrtos/ci:v0.27.5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
      - name: Build the sample_application binary
        run: |
          west init .
          west update
          cd app
          west build -b b_l4s5i_iot01a
      - name: Upload sample_application artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: zephyr-sample_application
          path: app/build/zephyr/zephyr.*
